#! /usr/bin/python

import vcf
from vcf import utils
import argparse
import csv
import re
from intervaltree import IntervalTree
from abc import ABCMeta, abstractmethod


class Genes(object):

    """
    The features class stores genes taken from a gff file
    """
    def __init__(self, gff):
        """

        :param gff: the file name of the gff file you want to import
        """
        self.gene_dict = gff

    @staticmethod
    def get_name(info):
        """
        import
        :param info:
        :return: Either the name of the Gene or the Orf number
        """
        match = re.search("Gene.+?;", info)
        if not match:
            match = re.search("Name.+?;", info)
        return match.group()[5:-1]

    @property
    def gene_dict(self):
        """

        :return: gene_dict
        """
        return self._gene_dict

    @gene_dict.setter
    def gene_dict(self, gff):
        """
        Sets the the features to a range tree of genes
        :param gff:

        """
        gd = {}
        with open(gff, "r") as infile:
            reader = csv.reader(infile, delimiter="\t")
            for r in reader:
                if ("#" not in r[0]) and (len(r) > 1) and (r[2] == "gene"):
                    gd.setdefault(r[0], IntervalTree())
                    gd[r[0]][int(r[3]):int(r[4])] = self.get_name(r[8])
        self._gene_dict = gd


class Child(object):
    def __init__(self, name, al, gt, gt_data, dp, mq, mq0, ref, effect):
        """

        :param name:
        :param al:
        :param gt:
        :param gt_data:
        """
        self.name = name
        self.al = al
        self.gt = gt
        self.gt_data = gt_data
        self.mutation = None
        self.dp = dp
        self.mq = mq
        self.mq0 = mq0
        self.ref = ref
        self.effect = effect

    @property
    def formatted_al(self):
        formatted_al = ''
        if self.gt == 0 or self.gt == 2:
            formatted_al = self.al*2
        else:
            formatted_al = self.ref + self.al
        return formatted_al

    @property
    def formatted_gt(self):
        formatted_gt = ""
        if self.gt == 0:
            formatted_gt = "0/0"
        if self.gt == 1:
            formatted_gt = "0/1"
        else:
            formatted_gt = "1/1"
        return formatted_gt

    def __str__(self):
        return "Name:" + self.name + " Allele:" + str(self.al) + " Genotype:" + str(self.gt) + " MutationType:" + str(
            self.mutation)


class Row(object):

    features = None
    file_names = []
    parent_name = None

    def __init__(self, chrom, pos, parent, children):

        self.chrom = chrom
        self.pos = pos
        self.parent = parent
        self.children = children
        self.compare_children()

    @staticmethod
    def extract_name(file_name):
        """

        :param file_name:
        :return:
        """
        start_index = file_name.rfind("/") + 1
        end_index = file_name.find(".")
        return file_name[start_index:end_index]

    @property
    def gene(self):
        """
        The name of the gene that contains this position.
        :return: the gene that that contains this position. Returns a null string if the position is intergenic.
        """
        gene = ""
        feature = self.features[self.chrom][self.pos]
        if feature:
            gene = feature.pop()[2]
        return gene

    def compare_children(self):
        """
        determines the each child's mutation type and adds it to the child instance
        :return:
        """
        for child in self.children:
            mut = ''
            if self.parent.gt == 1 and child.gt == 0:
                mut = 'loh'
            elif self.parent.gt != 1 and child.gt == 1:
                mut = 'heterozygous'
            elif self.parent.al != child.al:
                mut = 'homozygous'
            child.mutation = mut


class VCFWriter:

    file_names = []
    readers = []

    def __init__(self, file_names, readers):
        """
        Writes the data to a vcf
        :param file_names:
        :param readers:
        """
        self.outfiles = [open(f[:-3]+".comparevcf.vcf", "w") for f in file_names[1:]]
        self.writers = [vcf.Writer(filename, readers[idx+1]) for idx, filename in
                        enumerate(self.outfiles)]

    def __enter__(self):
        """

        :return:
        """
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """
        Closes all the files
        :param exc_type:
        :param exc_val:
        :param exc_tb:
        :return:
        """
        for f in self.outfiles:
            f.close()

    def write_row(self, row):
        """
        writes a Row() to the vcf
        :param row:
        :return:
        """
        formatted_row = self.format_row(row)
        for idx, rec in enumerate(formatted_row):
            self.writers[idx].write_record(rec)


    @staticmethod
    def format_row(row):
        """

        :param row:
        :return: a list of PyVCF Record objects. There is a different record for every child.
        """
        new_recs = []
        for idx, child in enumerate(row.children):

            if child.mutation:
                alt = [vcf.model._Substitution([child.al])]

                if not row.parent:
                    ref = row.ref
                else:
                    ref = row.parent.al

                new_rec=vcf.model._Record(row.chrom, row.pos, ref, "", alt, "", "PASS",
                                         "", "", None)

                call = vcf.model._Call(new_rec, child.name, child.gt_data)

                new_rec.samples = [call]
                new_recs.append(new_rec)
        return new_recs


class CSVWriter():

    def __init__(self, outfile):
        """
        Writes the data to a csv file
        :param outfile:
        """
        if outfile:
            self.outfile = open(outfile, "w")

        self.csv_writer = csv.writer(self.outfile)
        self.csv_writer.writerow(["Progeny", "Chromosome", "Position", "ParentAlleles", "ChildAlleles", "Gene","Mutation","ParentDepth","ChildDepth"])

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """
        closes the outfile
        :param exc_type:
        :param exc_val:
        :param exc_tb:
        :return:
        """
        self.outfile.close()

    def write_row(self,row):
        """

        :param row:
        :return:
        """

        formatted_rows = self.format_row(row)
        self.csv_writer.writerows(formatted_rows)

    @staticmethod
    def format_row(row):
        """
        Returns a list of lists. Where each list represents the csv row for a child.
        :param row:
        :return:
        """
        formatted_rows = []
        for child in row.children:
            if child.mutation:
                csv_row = [child.name, row.chrom, row.pos, child.ref, row.parent.formatted_al,
                           child.formatted_al, row.gene, child.mutation, row.parent.dp, child.dp]
                formatted_rows.append(csv_row)
        return formatted_rows


class Comparator():
    __metaclass__ = ABCMeta

    def __init__(self, args):
        """
        Abstract class that iterates through all the VCF and generates Rows
        :param args:
        """
        self.infiles = args.infiles
        self.location = args.location
        self.files = [open(f, "r") for f in args.infiles]
        self.readers = [self.get_location(vcf.Reader(f)) for f in self.files]
        self.rows_processed = 0

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """
        Closes all the files
        :param exc_type:
        :param exc_value:
        :param traceback:
        :return:
        """
        for f in self.files:
            f.close()

    def __iter__(self):
        return self

    @abstractmethod
    def next(self):

        pass

    def __next__(self):
        return self.next()
        if self.rows_processed % 100000 == 0:
            print "Processed " + str(self.processed_rows) + " rows." 

    def get_location(self, reader):
        """
        Uses an index to select only a portion of the genome
        :param reader:
        :return: a new reader that one contains a specific portion of the genome
        """
        adjusted_reader = reader
        if self.location:
            loc_chr = self.location[0]
            start = int(self.location[1])
            end = int(self.location[2])
            adjusted_reader = reader.fetch(loc_chr, start, end)
        return adjusted_reader

    @staticmethod
    def extract_name(file_name):
        """
        :param file_name:
        :return:
        """
        start_index = file_name.rfind("/") + 1
        end_index = file_name.find(".")
        return file_name[start_index:end_index]


class MultiSampleComparator(Comparator):

    def __init__(self, args):
        """

        :param args:
        """
        Comparator.__init__(self, args)

    def next(self):
        """

        :return: a MultiSampleRow()
        """
        rec=next(self.readers[0])
        return Row(rec)


class MultiFileComparator(Comparator):

    def __init__(self, args):
        """

        :param args:
        """
        Comparator.__init__(self, args)
        self.walker = vcf.utils.walk_together(*self.readers)

    def next(self):
        """

        :return: a Row() creates from the walker's row
        """
        while True:
            recs = self.walker.next()
            if self.filter_rec(recs[0]):
                chrom = recs[0].CHROM
                pos = recs[0].POS
                parent = self.make_child(0,recs[0])
                children = self.make_children(recs)

                row = Row(chrom, pos, parent, children)
                return row

    def make_children(self,recs):
        children = []
        for idx,rec in enumerate(recs[1:]):
            if self.filter_rec(rec):
                children.append(self.make_child(idx+1, rec))
        return children
    
    @staticmethod
    def filter_rec(rec):
        if not rec:
            return False
        if len(rec.ALT)>1:
            return False
        if len(rec.REF)>1:
            return False
        if rec.FILTER:
            return False
	if "DP" not in rec.INFO:
            return False
        if rec.INFO["DP"] < 15:
            return False
        if "HaplotypeScore" in rec.INFO and rec.INFO["HaplotypeScore"]>13:
            return False
        return True

    def make_child(self, idx, rec):
        name = self.extract_name(self.infiles[idx])
        ref = rec.REF
        try:
            dp = rec.INFO["DP"]
            mq = rec.INFO["MQ"]
            mq0 = rec.INFO["MQ0"]
        except KeyError:
            dp = ''
            mq = ''
            mq0 = ''
        try:
            al = rec.samples[0].gt_bases[-1]
            gt = rec.samples[0].gt_type
            gt_data = rec.samples[0].data
            effect = self.get_effect(rec)
        except TypeError:
            al = rec.REF
            gt = 0
            gt_data = None
            effect = 0
        return Child(name, al, gt, gt_data, dp, mq, mq0, ref, effect)

    @staticmethod
    def get_effect(rec):
        desired_annotations = ["synonymous_variant", "stop_gained", "missense_variant"]
        effects = []
        if "ANN" in rec.INFO:
            ann_info = rec.INFO["ANN"]
            annotations = [ann.split("|") for ann in ann_info.split(",")]
            for annotation in annotations:
                if annotation[1] in desired_annotations:
                    effect = (annotation[1], annotation[10])
                    effects.append(effect)
        return effects


def main():
    parser = argparse.ArgumentParser(
        description="Compare one parent vcf to one or more child vcfs. All files should be bgzipped and tabix indexed.")
    parser.add_argument("infiles", nargs="+", help='''The locations of all files to be compared.
                        If only one file is given, the file is assumed to be a multisample vcf.
                        In this case, specify the call name of the parent. If there are multiple files,
                        the parent is assumed to be the first, unless a different file name is given by the parent
                        option.''')
    parser.add_argument("--parent", help="The call name or filename of the parent")
    parser.add_argument("--pedigree", help=(
        "The relationship between parents and children can also be specified with a\n"
        "     json file of the form:\n"
        "    {parent:/file/path/to/parent.vcf,children:[file/path/to/first/child.vcf,file/path/to/second/child.vcf]}"))
    parser.add_argument("--location", nargs=3,
                        help='''The chromesome, start position and end position that you would like to pull out. For
                        example: 5 44567 44789. If you specify this option the file must be tabix indexed.''')
    parser.add_argument("--gff", default="", help='''Path of GFF for features''')
    parser.add_argument("--csv", action='store_true', help='''If you want a vcf output, otherwise will be a csv''')
    parser.add_argument("--outfile",
                        help='''Name of the outfile. By default the outfile is the name of the parent followed by the
                        extension''')

    args = parser.parse_args()

    if args.gff:
        feat = Genes(args.gff)
        Row.features = feat.gene_dict

    if len(args.infiles) > 1:
        comp = MultiFileComparator
    else:
        comp = MultiSampleComparator

    with comp(args) as cp:
        if args.csv:
            writer = CSVWriter
            writer_args = [args.outfile]
        else:
            writer = VCFWriter
            writer_args = [args.infiles, cp.readers]
        with writer(*writer_args) as wr:
            for row in cp:
                row.compare_children()
                wr.write_row(row)

if __name__ == "__main__":
    main()
